
<!DOCTYPE html>
<html>
<head>
<title>Syarat & Ketentuan</title>
<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body class="bg-light">
<div  style="height: 50px;background: #ddd" >
	<div class="text-center"><h1 style="text-shadow: #fff">Gita Smart School</h1></div>

</div>
<div class="container">
	<br>
	
		<h4 style="text-align: center;">Ketentuan Penggunaan</h4>
		
			Dengan mengunduh, memasang, dan/atau menggunakan Aplikasi GITA Smart School ("Aplikasi"), anda setuju bahwa anda telah membaca, memahami dan menerima dan menyetujui Ketentuan Penggunaan ini ("Ketentuan Penggunaan"). Ketentuan Penggunaan ini merupakan suatu perjanjian sah antara anda dan PT Gita Pratama Nusantara dan Layanan dan Aplikasi (sebagaimana didefinisikan di bawah ini) berlaku pada kunjungan dan penggunaan anda pada situs web kami di www.gitawisata.com ("Situs web").<br>
			Silakan membatalkan akun anda (jika anda telah mendaftar untuk Aplikasi) dan secara permanen menghapus aplikasi dari perangkat anda jika anda tidak setuju atau tidak ingin masuk ke dalam Ketentuan Penggunaan.<br>
			MOHON ANDA MEMERIKSA KETENTUAN PENGGUNAAN DAN KEBIJAKAN PRIVASI KAMI DENGAN SEKSAMA SEBELUM MENGUNDUH APLIKASI ATAU MENGGUNAKAN LAYANAN KAMI UNTUK PERTAMA KALI.<br>
		<h6 style="text-align: center;">	HAL-HAL UMUM</h6>
			1.	PT Gita Pratama Nusantara adalah suatu perseroan yang didirikan berdasarkan hukum Negara Republik Indonesia ("kami" atau "milik kami").<br>
			2.	Aplikasi ini merupakan aplikasi perangkat lunak yang berfungsi sebagai sarana untuk menemukan layanan Aplikasi ini menawarkan informasi tentang layanan yang ditawarkan oleh Penyedia Layanan. Jenis layanan yang dapat diminta melalui Aplikasi adalah:<br>
			a.	Travel Shuttle;<br>
			b.	Mobil Rent Car;<br>
			c.	Motorcycle Rent;<br>
			d.	Bus Reguler; <br>
			e.	Bus Rental;<br>
			f.	Open Trip ; dan<br>
			g.	Layanan lain yang dapat kami tambahkan dari waktu ke waktu ("Layanan").<br>
				Aplikasi ini memungkinkan anda untuk mengirimkan permintaan untuk suatu Layanan kepada Penyedia Layanan. Penyedia Layanan juga memiliki kebijakannya sendiri dan menyeluruh untuk memilih dan menerima arahan-arahan yang diberikan oleh Aplikasi tersebut. Jika Penyedia Layanan menerima permintaan anda, Aplikasi akan memberitahu anda dan memberikan informasi mengenai Penyedia Layanan - termasuk nama Penyedia Layanan, nomor polisi kendaraannya, dan penilaian pelayanan pelanggan - dan kemampuan untuk menghubungi Penyedia Layanan melalui telepon. Aplikasi ini juga memungkinkan anda untuk melihat perkembangan Penyedia Layanan menjuju titik penjemputan, secara langsung/real time.<br>
				UNTUK MENGHINDARI KERAGU-RAGUAN, KAMI ADALAH PERUSAHAAN TEKNOLOGI, BUKAN PERUSAHAAN TRANSPORTASI ATAU AGENT PERJALANAN WISATA DAN KAMI TIDAK MEMBERIKAN LAYANAN TRANSPORTASI ATAU PERJALANAN WISATA. Kami tidak mempekerjakan Penyedia Layanan dan kami tidak bertanggung jawab atas setiap tindakan dan/atau kelalaian Penyedia Layanan. Aplikasi ini hanya merupakan sarana untuk memudahkan pencarian atas Layanan. Adalah tergantung pada Penyedia Layanan untuk menawarkan Layanan kepada anda dan tergantung pada anda apakah anda akan menerima tawaran Layanan dari Penyedia Layanan.<br><br>
				KETENTUAN UNTUK MENGGUNAKAN APLIKASI<br>
				Anda menyatakan dan menjamin bahwa anda adalah individu yang secara hukum berhak untuk mengadakan perjanjian yang mengikat berdasarkan hukum Negara Republik Indonesia, khususnya Ketentuan Penggunaan, untuk menggunakan Aplikasi dan bahwa anda telah berusia minimal 21 tahun atau sudah menikah dan tidak berada di bawah perwalian. Jika tidak, kami atau Penyedia Layanan terkait, berhak berdasarkan hukum untuk membatalkan perjanjian yang dibuat dengan anda. Anda selanjutnya menyatakan dan menjamin bahwa anda memiliki hak, wewenang dan kapasitas untuk menggunakan Layanan dan mematuhi Ketentuan Penggunaan. Jika anda mendaftarkan atas nama suatu badan hukum, anda juga menyatakan dan menjamin bahwa anda berwenang untuk mengadakan, dan mengikatkan diri entitas tersebut pada Ketentuan Penggunaan ini dan mendaftarkan untuk Layanan dan Aplikasi.
				Kami mengumpulkan dan memproses informasi pribadi anda, seperti nama, alamat surat elektronik (surel / e-mail), dan nomor telepon seluler anda ketika anda mendaftar. Anda harus memberikan informasi yang akurat dan lengkap, memperbaharui informasi dan setuju untuk memberikan kepada kami bukti identitas apapun yang secara wajar dapat kami mintakan. Jika informasi pribadi yang anda berikan kepada kami ada yang berubah, misalnya, jika anda mengubah alamat surel, nomor telepon, atau jika anda ingin membatalkan akun anda, mohon perbaharui rincian informasi Anda dengan mengirimkan permintaan anda kepada kami. Kami akan, sepanjang yang dapat kami lakukan, memberlakukan perubahan yang diminta tersebut dalam waktu lima belas (15) hari kerja sejak diterimanya pemberitahuan perubahan.<br>
				Anda hanya dapat menggunakan Aplikasi ketika anda telah mendaftar pada Aplikasi tersebut. Setelah anda berhasil mendaftarkan diri, Aplikasi akan memberikan anda suatu akun pribadi yang dapat diakses dengan kata sandi yang anda pilih.
				Hanya anda yang dapat menggunakan akun anda sendiri dan anda berjanji untuk tidak memberikan wewenang kepada orang lain untuk menggunakan identitas anda atau menggunakan akun anda. Anda tidak dapat menyerahkan atau mengalihkan akun anda kepada pihak lain. Anda harus menjaga keamanan dan kerahasiaan kata sandi akun anda dan setiap identifikasi yang kami berikan kepada anda. Dalam hal terjadi pengungkapan atas kata sandi anda, dengan cara apapun, yang mengakibatkan setiap penggunaan yang tidak sah atau tanpa kewenangan atas akun atau identitas anda, pesanan yang diterima dari penggunaan yang tidak sah atau tanpa kewenangan tersebut masih akan dianggap sebagai pesanan yang sah, kecuali anda memberitahu kami tentang mengenai hal tersebut sebelum Penyedia Layanan memberikan Layanan yang diminta.<br>
				Anda hanya dapat memiliki satu akun Gita Smart School.<br>
				Informasi yang diberikan oleh Aplikasi tidak dapat diartikan sebagai suatu saran atau penawaran, keputusan untuk menggunakan Penyedia Layanan sepenuhnya berada di tangan anda. Anda bebas untuk memilih untuk menggunakan penyedia layanan lainnya.<br>
				Anda berjanji bahwa anda akan menggunakan Aplikasi hanya untuk tujuan yang dimaksud untuk mendapatkan Layanan. Anda tidak diperbolehkan untuk menyalahgunakan atau menggunakan Aplikasi untuk tujuan penipuan atau menyebabkan ketidaknyamanan kepada orang lain atau melakukan pemesanan palsu.<br>
				Anda tidak diperkenankan untuk membahayakan, mengubah atau memodifikasi Aplikasi dan/atau Situs web atau mencoba untuk membahayakan, mengubah atau memodifikasi Aplikasi dan/atau Situs web dengan cara apapun. Kami tidak bertanggung jawab jika anda tidak memiliki perangkat yang sesuai atau jika anda telah mengunduh versi Aplikasi yang salah untuk perangkat anda. Kami berhak untuk melarang anda untuk menggunakan Aplikasi lebih lanjut jika anda menggunakan Aplikasi dengan perangkat yang tidak kompatibel/cocok atau tidak sah atau untuk tujuan lain selain daripada tujuan yang dimaksud untuk penggunaan Aplikasi ini. Anda berjanji bahwa anda hanya akan menggunakan suatu jalur akses yang diperbolehkan untuk anda gunakan.
				Anda akan menjaga kerahasiaan dan tidak akan menyalahgunakan informasi yang anda terima dari penggunaan Aplikasi tersebut. Anda akan memperlakukan Penyedia Layanan dengan hormat dan tidak akan terlibat dalam perilaku atau tindakan yang tidak sah, mengancam atau melecehkan ketika menggunakan layanan mereka.<br>
				Anda memahami dan setuju bahwa penggunaan Aplikasi oleh anda akan tunduk pula pada Kebijakan Privasi kami sebagaimana dapat diubah dari waktu ke waktu. Dengan menggunakan Aplikasi, Anda juga memberikan persetujuan sebagaimana dipersyaratkan berdasarkan Kebijakan Privasi kami.<br>
				Dengan memberikan informasi kepada kami, anda menyatakan bahwa anda berhak untuk memberikan kepada kami informasi yang akan kami gunakan dan berikan kepada Penyedia Layanan.<br>
				Aplikasi tidak boleh dipergunakan untuk mencari Layanan untuk:<br>
			 .	mengangkut dan/atau memperoleh dan/atau membeli barang yang dilarang oleh pejabat yang berwenang atau barang yang memerlukan lisensi atau izin tertentu dari pejabat yang berwenang untuk dikirimkan;<br>
			a.	mengangkut barang dari dan ke penjara;<br>
			b.	membeli dan/atau mengangkut binatang peliharaan atau binatang lain;<br>
			c.	membeli dan/atau mengangkut barang-barang ilegal atau berbahaya atau barang-barang curian, termasuk namun tidak terbatas pada barang-barang yang mengandung bahan berbahaya atau beracun, obat-obatan atau material terlarang/ilegal; dan<br>
				Anda harus mengemas dengan benar barang-barang yang rapuh, seperti gelas, keramik, kue atau makanan, untuk pengiriman. Kami maupun Penyedia Layanan tidak akan bertanggung jawab atas segala kerusakan, perubahan bentuk, pembengkokan, kadaluwarsa, pembusukan, bau, tumpahan atau ketidaklengkapan lain dari produk selama pengiriman yang disebabkan oleh kemasan atau pembungkusan yang kurang baik/sesuai.<br>
				Penyedia Layanan dapat meminta anda untuk membuka dan menunjukkan bagian dalam suatu paket untuk memastikan bahwa isinya adalah seperti yang anda nyatakan.<br>
				Penyedia Layanan berhak untuk menolak pesanan anda jika menurut penilaian pribadi Penyedia Layanan, ia mungkin tidak dapat melakukan pengiriman barang.<br>
				Anda menyatakan bahwa anda telah, adalah, atau akan menjadi pemilik yang sah atas barang yang akan dikirimkan. Barang yang dikirim bukan barang curian atau diperoleh secara tidak sah dan anda setuju untuk menjaga, mengganti kerugian dan membebaskan kami dan kami tidak bertanggung jawab atas barang yang dikirimkan oleh Penyedia Layanan yang mungkin melanggar peraturan perundang-undangan yang berlaku.<br>
				Kami dan/atau Penyedia Layanan yang terkait berhak menolak untuk menerima pesanan Anda jika kami memiliki alasan yang wajar untuk mencurigai bahwa anda telah, atau dengan menerima pesanan dari anda, anda akan melanggar Ketentuan Penggunaan ini atau hukum dan peraturan perundang-undangan yang berlaku.<br>
				Kami dapat, berdasarkan kebijakan kami, memberikan promosi-promosi yang dapat ditukar untuk manfaat terkait dengan penggunaan Aplikasi. Anda setuju bahwa anda hanya akan menggunakan promosi tersebut sebagaimana promosi tersebut dimaksudkan dan tidak akan menyalahgunakan, menggandakan, menjual atau mengalihkan promosi tersebut dengan cara apapun. Anda juga memahami bahwa promosi tidak dapat ditukarkan dengan uang tunai dan dapat berakhir pada tanggal tertentu, bahkan sebelum anda menggunakannya.<br>
				Mohon menginformasikan kepada kami jika anda tidak lagi memiliki kontrol atas akun anda, sebagai contoh akun anda dengan cara bagaimanapun diretas (hack) atau telepon anda dicuri, sehingga kami dapat membatalkan akun anda dengan sebagaimana mestinya. Mohon diperhatikan bahwa anda bertanggung jawab atas penggunaan akun anda dan anda mungkin dapat dimintakan tanggung jawabnya meskipun jika akun anda tersebut disalahgunakan oleh orang lain.<br><br>
				
				PEMBAYARAN<br>
				Pengunduhan dan/atau penggunaan Aplikasi ini adalah bebas biaya. Kami dapat memperkenalkan pengenaan biaya untuk <br>pengunduhan dan/atau penggunaan Aplikasi di setiap saat. Kami akan memberitahu anda tentang hal ini sebagaimana mestinya agar anda dapat memutuskan apakah anda ingin terus menggunakan Aplikasi tersebut atau tidak. Namun demikian, koneksi internet yang dibutuhkan untuk menggunakan Layanan, dan setiap biaya terkait (misalnya biaya data ponsel) yang ditimbulkan oleh penggunaan Layanan tersebut adalah tanggung jawab eksklusif anda dan semata-mata dibebankan kepada anda.
				Tarif yang berlaku untuk Layanan oleh Penyedia Layanan dapat ditemukan pada Situs dan melalui Aplikasi. Kami dapat mengubah atau memperbaharui tarif dari waktu ke waktu. Kami akan membantu Penyedia Layanan untuk menghitung biaya berdasarkan pesanan anda dan memberitahu anda tentang biaya atas nama Penyedia Layanan.<br>
				Anda setuju bahwa anda akan membayar Layanan yang diberikan kepada anda oleh Penyedia Layanan secara penuh.
			Pembayaran dapat dilakukan secara transfer atau dengan menggunakan Gita Smart School Credit anda. Semua pembayaran transfer harus dilakukan dalam Rupiah. Gita Smart School Credit dapat diperoleh dengan mentransfer jumlah yang anda inginkan ke rekening BRI kami di nomor 1157-01-000186-30-5 A/N PT. GITA PRATAMA NUSANTARA.<br>
				Gita Smart School Credit bukan merupakan tabungan dan karena itu tidak termasuk dalam pengaturan oleh Lembaga Penjamin Simpanan Indonesia (LPS). Karena Gita Smart School Credit dapat dikategorikan sebagai e-money berdasarkan peraturan perundang-undangan yang berlaku, penggunaan Gita Smart School Credit harus tunduk pada peraturan perundang-undangan yang berlaku.
				Jumlah maksimum Gita Smart School Credit anda adalah Rp5.000.000 (lima juta Rupiah) dan maksimum total nilai transaksi anda dalam sebulan adalah Rp20.000.000 (dua puluh juta Rupiah).<br>
				Gita Smart School Credit adalah dana Anda yang hanya dapat digunakan untuk pembayaran:<br>
			 .	Layanan Open Trip dan Transportasi yang disediakan oleh Penyedia Layanan; dan<br>
			biaya dari Penyedia Layanan dalam pelayanan Pembelanjaan Pribadi.<br>
				Gita Smart School dapat, dari waktu ke waktu, menambah jumlah Gita Smart School Credit anda di akun anda sebagai bagian dari promosinya (misalnya, kode rujukan / referral code). Namun demikian, ini hanya suatu nilai yang setara dengan nilai uang berdasarkan peraturan perundang-undangan yang berlaku dan tidak dapat diubah menjadi uang elektronik (e-money).<br>
				Ketika anda meminta untuk menggunakan Gita Smart School Credit sebagai alat pembayaran atas Layanan, anda dengan ini mengakui dan setuju untuk memberikan kami kuasa dan kewenangan penuh untuk memotong GITA WISAT<br>


				JAMINAN<br><br>
				Kami tidak memberikan pernyataan, jaminan atau garansi untuk dapat diandalkannya, ketepatan waktu, kualitas, kesesuaian, ketersediaan, akurasi atau kelengkapan dari Layanan, Situs web dan/atau perangkat lunak Aplikasi, termasuk namun tidak terbatas pada Layanan yang diperoleh atau berasal dari Penyedia Layanan melalui penggunaan Aplikasi tersebut. Kami tidak menyatakan atau menjamin bahwa (a) penggunaan Layanan dan/atau Aplikasi akan aman, tepat waktu, tanpa gangguan atau terbebas dari kesalahan atau beroperasi dengan kombinasi dengan perangkat keras lain, perangkat lunak, sistem atau data, (b) Layanan akan memenuhi kebutuhan atau harapan anda, (c) setiap data yang tersimpan akan akurat atau dapat diandalkan, (d) kualitas produk, layanan, informasi, atau diperoleh oleh anda melalui Aplikasi akan memenuhi kebutuhan atau harapan anda, (e) kesalahan atau kecacatan dalam Aplikasi akan diperbaiki, atau (f) aplikasi atau server(-server)) yang menyediakan Aplikasi terbebas dari virus atau komponen berbahaya lainnya, atau (g) â€‹â€‹Aplikasi melacak anda atau kendaraan yang digunakan oleh Penyedia Layanan. Layanan disediakan untuk anda terbatas hanya pada dasar "sebagaimana adanya". Semua kondisi, pernyataan dan jaminan, baik tersurat, tersirat, yang diwajibkan oleh undang-undang atau sebaliknya, termasuk, namun tidak terbatas pada, kesesuaian untuk tujuan tertentu, atau tidak adanya pelanggaran hak pihak ketiga, dengan ini dikecualikan dan dikesampingkan dengan batas tertinggi dan maksimum. Anda mengakui dan menyetujui bahwa seluruh risiko yang timbul dari penggunaan Layanan oleh anda tetap semata-mata dan sepenuhnya ada pada anda dan anda tidak akan memiliki hak untuk meminta ganti rugi apapun dari perusahaan.<br><br>
				TANGGUNG JAWAB KAMI<br>
				Kami tidak bertanggung jawab atas setiap cidera, kematian, kerusakan atau kerugian yang disebabkan oleh perilaku dari para Penyedia Layanan. Kami juga tidak bertanggung jawab atas kesalahan, termasuk pelanggaran lalu lintas, atau tindakan kriminal yang dilakukan oleh Penyedia Layanan selama pelaksanaan Layanan. Penyedia Layanan hanya merupakan mitra kerja kami, bukan pegawai, agen atau perwakilan kami.<br>
				Namun, kami peduli akan keselamatan pengguna Aplikasi dan, atas pertimbangan pribadi semata dan sepenuhnya, kami bersedia untuk memberikan bantuan keuangan jika pengguna mengalami kecelakaan, menderita cidera atau meninggal saat dijemput oleh Penyedia Layanan. Bantuan kami hanya berlaku sejak pengguna dijemput oleh Penyedia Layanan sampai pengguna mencapai tujuannya. Mohon mengingatkan Penyedia Layanan jika anda merasa tidak nyaman dengan cara Penyedia Layanan menyediakan layanan transportasi. Jumlah bantuan keuangan akan ditentukan berdasarkan kebijakan kami.<br>
				Kami menggunakan cara-cara teknis dan keamanan yang tepat dan wajar untuk menjaga Aplikasi aman dan terbebas dari virus dan kesalahan. Namun demikian, bagaimanapun efektifnya teknologi ini, tidak ada sistem keamanan yang tidak dapat ditembus. Oleh karena itu kami tidak dapat menjamin keamanan database kami dan kami juga tidak dapat menjamin bahwa informasi yang anda berikan tidak akan ditahan/terganggu saat sedang dikirimkan kepada kami.<br>
				Aplikasi ini dapat mengalami keterbatasan, penundaan, dan masalah-masalah lain yang terdapat dalam penggunaan internet dan komunikasi elektronik, termasuk perangkat yang digunakan oleh anda atau Penyedia Layanan rusak, tidak terhubung, berada di luar jangkauan, dimatikan atau tidak berfungsi. Kami tidak bertanggung jawab atas keterlambatan, kegagalan pengiriman, kerusakan atau kerugian yang diakibatkan oleh masalah-masalah tersebut.<br><br>
				PEMBATASAN TANGGUNG JAWAB<br>
				Setiap tuntutan terhadap kami dalam hal apapun oleh anda, akan dibatasi dengan jumlah total yang sebenarnya dibayar oleh dan/atau terhutang pada Anda ketika menggunakan Layanan selama peristiwa yang menimbulkan klaim tersebut. Dalam hal apapun kami dan/atau pemberi lisensi kami tidak akan bertanggung jawab kepada anda atau siapa pun atas biaya, bunga, kerusakan atau kerugian dalam segala jenis atau bentuk(termasuk cidera pribadi, gangguan emosi dan hilangnya data, barang, pendapatan, keuntungan, penggunaan atau keuntungan ekonomi lainnya). Perusahaan dan/atau pemberi lisensinya tidak akan bertanggung jawab atas kerugian, kerusakan atau cidera yang mungkin ditimbulkan oleh atau disebabkan oleh anda atau pada setiap orang untuk siapa anda telah memesan Layanan, termasuk namun tidak terbatas pada kerugian, kerusakan atau cidera yang timbul dari, atau dengan cara apapun sehubungan dengan Layanan dan/atau Aplikasi, termasuk namun tidak terbatas pada penggunaan atau ketidakmampuan untuk menggunakan Layanan dan/atau Aplikasi.<br>
				Anda secara tegas mengesampingkan dan melepaskan kami dari setiap dan semua kewajiban, tuntutan atau kerusakan yang timbul dari atau dengan cara apapun sehubungan dengan Penyedia Layanan. Perusahaan tidak akan menjadi pihak dalam sengketa, negosiasi sengketa antara anda dan Penyedia Layanan. Tanggung jawab untuk keputusan yang anda buat atas Layanan yang ditemukan melalui Aplikasi merupakan tanggung jawab dan melekat seutuhnya dengan dan pada anda. Anda secara tegas mengesampingkan dan melepaskan kami dari setiap dan semua kewajiban, tuntutan, penyebab tindakan, atau kerusakan yang timbul dari penggunaan Layanan, perangkat lunak dan/atau Aplikasi, atau dengan cara apapun terkait dengan Penyedia Layanan yang diperkenalkan kepada anda melalui Aplikasi.<br>
				Kualitas Layanan yang diperoleh melalui penggunaan Aplikasi ini sepenuhnya menjadi tanggung jawab Penyedia Layanan yang pada akhirnya memberikan Layanan untuk anda. Anda memahami, oleh karena itu, bahwa dengan menggunakan Aplikasi ini, Anda dapat dihadapkan pada transportasi yang berpotensi berbahaya, ofensif, berbahaya bagi anak di bawah umur, tidak aman atau tidak pantas, dan bahwa Anda menggunakan layanan atas risiko anda sendiri.<br><br>
				GANTI RUGI<br>
				Dengan menggunakan Aplikasi ini, anda setuju bahwa anda akan membela, memberikan ganti rugi dan membebaskan kami, pemberi lisensi, afiliasi, dan masing-masing dari petugas, direktur, komisaris, karyawan, pengacara dan agen kami dari dan terhadap setiap dan semua klaim, biaya, kerusakan, kerugian, kewajiban dan biaya (termasuk biaya dan ongkos pengacara) yang timbul dari atau sehubungan dengan: (a) penggunaan Layanan dan/atau Aplikasi oleh anda, hubungan anda dengan Penyedia Layanan, penyedia pihak ketiga, mitra, pemasang iklan dan/atau sponsor, atau (b) pelanggaran atas atau tidak dipatuhinya salah satu Ketentuan Penggunaan atau peraturan perundang-undangan yang berlaku, baik yang disebutkan di sini atau tidak atau (c) pelanggaran anda terhadap hak-hak pihak ketiga, termasuk Penyedia Layanan pihak ketiga yang diatur melalui Aplikasi, atau (d) penggunaan atau penyalahgunaan Aplikasi. Kewajiban pembelaan dan pemberian ganti rugi ini akan tetap berlaku walaupun Ketentuan Penggunaan dan penggunaan Situs oleh anda telah berakhir.<br><br>
				PERIJINAN<br>
				Dengan tergantung pada kepatuhan anda pada Ketentuan Penggunaan, kami memberikan anda ijin yang terbatas, non-eksklusif, tidak dapat dipindahtangankan, tidak dapat dialihkan, tidak dapat disublisensikan, ijin yang dapat ditarik untuk mengunduh dan memasang salinan Aplikasi pada suatu perangkat bergerak tunggal yang anda miliki atau kontrol dan menjalankan salinan Aplikasi semata-mata untuk kebutuhan pribadi, non-komersial anda sendiri.<br>
				Anda tidak diperkenankan (i) menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, mendistribusikan, memberikan lisensi, menjual, mengalihkan, menampilkan di muka umum, membuat ulang, mentransmisikan, memindahkan, menyiarkan, menguraikan, atau membongkar bagian manapun dari atau dengan cara lain yang mungkin mengeksploitasi Aplikasi, kecuali sebagaimana diperbolehkan dalam Ketentuan Penggunaan ini, (ii) memberikan lisensi, mensublisensikan, menjual, menjual kembali, memindahkan, mengalihkan, mendistribusikan atau mengeksploitasi secara komersial atau membuat tersedia kepada pihak ketiga Aplikasi dan / atau perangkat lunak dengan cara; (iii) menciptakan "link" internet ke Aplikasi atau "frame" atau "mirror" setiap perangkat lunak pada server lain atau perangkat nirkabel atau yang berbasis internet; (iv) merekayasa ulang atau mengakses perangkat lunak kami untuk (a) membangun produk atau layanan tandingan, (b) membangun produk dengan menggunakan ide, fitur, fungsi atau grafis sejenis Aplikasi, atau (c) menyalin ide, fitur , fungsi atau grafis Aplikasi, (v) meluncurkan program otomatis atau script, termasuk, namun tidak terbatas pada, web spiders, web crawlers, web robots, web ants, web indexers, bots, virus atau worm, atau segala program apapun yang mungkin membuat beberapa permintaan server per detik, atau menciptakan beban berat atau menghambat operasi dan/atau kinerja Aplikasi, (vi) menggunakan robot, spider, pencarian situs/aplikasi pengambilan kembali, atau perangkat manual atau otomatis lainnya atau proses untuk mengambil, indeks, "tambang data" (data mine), atau dengan cara apapun memperbanyak atau menghindari struktur navigasi atau presentasi dari aplikasi atau isinya; (vii) menerbitkan, mendistribusikan atau memperbanyak dengan cara apapun materi yang dilindungi hak cipta, merek dagang, atau informasi yang dimiliki lainnya tanpa memperoleh persetujuan terlebih dahulu dari pemilik hak milik, (viii) menghapus setiap hak cipta, merek dagang atau pemberitahuan hak milik lainnya yang terkandung dalam aplikasi. Tidak ada lisensi atau hak yang diberikan kepada anda dengan implikasi berdasarkan hak kekayaan intelektual dimiliki atau dikendalikan oleh kami atau pemberi lisensi kami, kecuali untuk lisensi dan hak tersebut secara tegas diberikan dalam Ketentuan Penggunaan ini.<br>
				Anda (i) tidak akan mengirim spam atau pesan yang bersifat duplikasi atau tidak diminta yang melanggar hukum berlaku; (ii) tidak akan mengirim atau menyimpan materi yang melanggar, cabul, mengancam, memfitnah, atau melanggar hukum atau bersifat sadis, termasuk namun tidak terbatas pada bahan berbahaya bagi anak-anak atau yang melanggar hak privasi pihak ketiga; (iii) tidak akan mengirim bahan yang mengandung virus piranti lunak, worm, trojan horses atau kode komputer berbahaya lainnya, dokumen/file, script, agen atau program; (iv) tidak mengganggu atau mengacaukan integritas atau kinerja Aplikasi atau data di dalamnya; (v) tidak mencoba untuk mendapatkan akses yang tidak sah ke Aplikasi atau sistem atau jaringan terkait; (vi) tidak berkedok sebagai orang atau badan lain atau menggambarkan diri anda sebagai afiliasi seseorang atau suatu badan; dan (vii) menahan diri untuk terlibat dalam tindakan yang mungkin bisa merusak reputasi kami atau dianggap dapat merusak reputasi kami.<br>
				Kami akan memiliki hak untuk menyelidiki dan menuntut setiap pelanggaran di atas sepanjang yang dimungkinkan oleh hukum. Kami dapat melibatkan dan bekerja sama dengan pihak penegak hukum dalam menuntut pengguna yang melanggar Ketentuan Penggunaan ini. Anda mengakui bahwa kami tidak memiliki kewajiban untuk memonitor akses anda ke atau penggunaan Situs web atau Aplikasi, tapi kami memiliki hak untuk melakukannya untuk tujuan pengoperasian Situs web dan Aplikasi, untuk memastikan kepatuhan dengan Ketentuan Penggunaan ini, atau untuk mematuhi peraturan yang berlaku atau perintah atau persyaratan dari pengadilan, lembaga administratif atau badan pemerintahan lainnya.<br><br>
				HAL-HAL TERKAIT KEKAYAAN INTELEKTUAL<br>
				Gita Smart School, termasuk nama dan logo, Aplikasi dan Layanan, dilindungi oleh hak cipta, merek dagang dan hak-hak lain yang disediakan berdasarkan hukum Negara Republik Indonesia. Kami (dan pemberi lisensi kami, sebagaimana berlaku) secara eksklusif memiliki semua hak, kepemilikan dan kepentingan dalam dan terhadap Aplikasi, termasuk semua hak kekayaan intelektual terkait.<br>
				Tanpa menyimpang dari hak kami berdasarkan hukum yang berlaku atau Ketentuan Penggunaan, anda diberitahukan bahwa setiap berusaha atau pelanggaran nyata atas ketentuan ini akan mengakibatkan penghentian semua hak anda di bawah Ketentuan Penggunaan. Jika anda menghindari salah satu cara yang kami ambil untuk melindungi layanan dari penggunaan secara tidak sah, anda harus segera menghentikan setiap dan semua penggunaan Layanan, dan anda setuju untuk melakukannya.<br><br>
				PENGAKHIRAN<br>
				Anda tidak berkewajiban untuk menggunakan Aplikasi dan dapat memilih untuk berhenti menggunakannya setiap saat dengan membatalkan akun anda dan secara permanen menghapus aplikasi dari perangkat anda, sehingga menonaktifkan penggunaan Aplikasi tersebut. Ketentuan Penggunaan secara otomatis berakhir ketika anda secara permanen menghapus aplikasi dari perangkat.<br>
				Anda dapat mengakhiri akun anda dengan memberitahu kami maksud anda untuk membatalkan akun anda. Kami akan mencoba untuk melakukan yang terbaik untuk menyelesaikan penghentian, termasuk mengembalikan Gita Smart School Credit anda (tidak termasuk jumlah yang diperoleh dari rujukan (referral code) atau promosi lainnya) dalam waktu 15 (lima belas) hari kerja.
				Kami berhak untuk segera menangguhkan, membatasi atau menghentikan Ketentuan Penggunaan dan penggunaan Aplikasi jika kami memiliki alasan untuk mencurigai bahwa anda telah melanggar ketentuan dari Ketentuan Penggunaan ini atau peraturan perundang-undangan yang berlaku.<br>
				Jika anda secara permanen menghapus aplikasi atau berhenti menggunakan Aplikasi secara permanen, melalui pemberitahuan kepada kami dalam 14 (empat belas) hari kerja sebelum penghapusan atau penghentian, saldo Gita Smart School Credit anda dapat ditarik, namun terbatas pada nilai uang elektronik anda dan tidak termasuk jumlah nilai yang setara dengan nilai uang. Dalam hal kematian, ahli waris anda yang sah dengan pemberitahuan kepada kami dalam 14 (empat belas) hari kerja setelah kematian, dengan pernyataan yang sah yang dibuat sesuai dengan peraturan perundang-undangan yang berlaku atau keputusan pengadilan yang final dan mengikat, dapat mengklaim saldo Gita Smart School Credit Anda, namun terbatas pada nilai uang elektronik anda dan tidak termasuk jumlah nilai yang setara dengan nilai uang.<br><br>
				LAIN-LAIN<br>
				Pengesampingan atau toleransi atau kegagalan kami untuk mengklaim suatu pelanggaran ketentuan dari Ketentuan Penggunaan ini atau untuk melaksanakan hak yang dinyatakan oleh Ketentuan Penggunaan ini atau hukum yang berlaku, tidak akan dianggap sebagai pengesampingan sehubungan dengan pelanggaran berikutnya dari setiap ketentuan dari Ketentuan Penggunaan ini.
				Ketentuan Penggunaan ini disusun dalam bahasa Inggris dan bahasa Indonesia, kedua versi akan mengikat anda dan kami. Dalam hal terdapat ketidaksesuaian antara versi bahasa Indonesia dan versi bahasa Inggris, versi bahasa Indonesia yang akan berlaku.<br>
				Anda tidak dapat memindahkan atau mengalihkan hak anda berdasarkan Ketentuan Penggunaan, tanpa persetujuan tertulis sebelumnya dari kami. Kami dapat mengalihkan hak kami berdasarkan Ketentuan Penggunaan kepada pihak semata-mata dan mutlak menurut kebijakan kami.<br>
				Jika ada istilah berdasarkan Ketentuan Penggunaan yang dianggap tidak sah, tidak berlaku atau tidak dapat dilaksanakan, baik secara keseluruhan atau sebagian, berdasarkan pengundangan atau ketentuan perundang-undangan, istilah atau bagian dari istilah tersebut akan, sepanjang, dianggap bukan bagian dari Ketentuan Penggunaan ini, namun legalitas, keabsahan atau keberlakuan dari Ketentuan Penggunaan selebihnya tidak akan terpengaruhi.<br>
				Ketentuan Penggunaan ini diatur oleh dan ditafsirkan berdasarkan hukum Negara Republik Indonesia. Setiap dan semua sengketa yang timbul dari penggunaan layanan kami akan diatur oleh yurisdiksi eksklusif dari Pengadilan Negeri Jakarta Selatan.
				Ketentuan Penggunaan ini dapat dimodifikasi dan diubah dari waktu ke waktu. Kami akan memberitahu anda melalui Aplikasi dan/atau email atas modifikasi, dan/atau perubahan atas Ketentuan Penggunaan. Penggunaan Aplikasi secara terus menerus setelah diterimanya pemberitahuan ini merupakan persetujuan dan penerimaan anda atas modifikasi, dan/atau perubahan.<br><br>
			

	
	<br>

	
	
</div>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>
